rootProject.name = "sdm-2026-27"
include("part-01-oop-in-java")
include("part-02-behavior-parameterization")
include("part-03-streams")
include("part-04-swing-basics")
include("part-05-swing-components")
//include("part-06-multithreading-in-swing")
//include("part-07-mvc-humble-object")
//include("part-08-test-doubles")
include("part-09-gui-testing")
include("part-10-acceptance-testing")
