rootProject.name = "sdm-2025-26"
include("part-01-hello-world")
include("part-02-data-types-operators-flow-control")
include("part-03-oop")
include("part-04-oop-in-java")
include("part-05-record-enum-wrapper-generics")
include("part-06-collections")
include("part-07-exceptions")
include("part-08-behavior-parameterization")
include("part-09-acceptance-testing")
include("part-10-streams")
include("part-11-input-output")
include("part-12-third-party-libraries")
include("part-13-swing-basics")
include("part-14-swing-components")
include("part-15-gui-testing")
