rootProject.name = "sdm-2025-26"
include("part-01-hello-world")
include("part-02-data-types-operators-flow-control")
include("part-03-oop")
include("part-04-oop-in-java")
include("part-05-collections")
include("part-06-exceptions")
include("part-07-behavior-parameterization")
include("part-08-acceptance-testing")
include("part-09-streams")
include("part-10-input-output")
include("part-11-swing-basics")
include("part-12-swing-components")
include("part-13-gui-testing")